import { useState } from 'react'
import { DifficultyControl } from '../../components/DifficultyControl'
import { TrackPicker } from '../../components/TrackPicker'
import { getTrack, makeDeck, matchCards, tracks, type Difficulty, type TrackId } from '../../game'
export function MatchingGame({difficulty,onDifficultyChange,onMatch}:{difficulty:Difficulty;onDifficultyChange:(value:Difficulty)=>void;onMatch:()=>void}){
  const [trackId,setTrackId]=useState<TrackId>('math');const [deck,setDeck]=useState(()=>makeDeck());const [open,setOpen]=useState<string[]>([]);const track=getTrack(trackId);const [message,setMessage]=useState(track.instruction)
  const start=(nextTrack:TrackId=trackId,nextDifficulty:Difficulty=difficulty)=>{const next=getTrack(nextTrack);const samePack=nextTrack===trackId&&nextDifficulty===difficulty;const currentPairs=samePack?[...new Set(deck.map(card=>card.pairId))]:[];setTrackId(nextTrack);onDifficultyChange(nextDifficulty);setDeck(makeDeck(nextTrack,nextDifficulty,Math.random,currentPairs));setOpen([]);setMessage(next.instruction)}
  const choose=(id:string)=>{if(open.length===2)return;const card=deck.find(c=>c.id===id);if(!card||card.matched||open.includes(id))return;const next=[...open,id];setOpen(next);if(next.length===2){const result=matchCards(deck,next);if(result.matched){setDeck(result.deck);setOpen([]);setMessage('Rätt! Bra jobbat!');onMatch()}else{setMessage('Nästan! Försök igen');window.setTimeout(()=>setOpen([]),650)}}}
  return <><TrackPicker items={tracks} activeId={trackId} onSelect={id=>start(id,difficulty)}/><section className="hero"><div><p className="eyebrow">{track.name.toUpperCase()} · NIVÅ {difficulty}</p><h2>Parjakten</h2><p aria-live="polite">{message}</p></div><div className="actions"><DifficultyControl value={difficulty} onChange={level=>start(trackId,level)}/><button className="reset" onClick={()=>start()}>Blanda om</button></div></section><section className="game" aria-label={`Memory: ${track.name}`}>{deck.map(card=>{const shown=card.matched||open.includes(card.id);return <button data-testid={card.id} aria-label={shown?card.label:'Dolt kort'} disabled={card.matched} onClick={()=>choose(card.id)} className={shown?'card shown':'card'} key={card.id}>{shown?<span>{card.label}</span>:'✦'}</button>})}</section></>
}
