import { expect,test } from '@playwright/test'
test.beforeEach(async({page})=>{await page.addInitScript(()=>{if(!localStorage.getItem('mega-profiles'))localStorage.setItem('mega-profiles',JSON.stringify([{id:'explorer-1',name:'Räven',level:1,stars:0},{id:'explorer-2',name:'Björnen',level:1,stars:0}]))})})
test('switches profile, subject and level while progress persists',async({page})=>{
  await page.goto('/');await expect(page.getByRole('heading',{name:'Familjens lärhub'})).toBeVisible();await page.locator('.profile-select',{hasText:'Björnen'}).click();await page.getByRole('button',{name:'Spela'}).click();await page.getByRole('button',{name:'Parjakten'}).click();await page.getByRole('button',{name:/Engelska/}).click();await expect(page.getByText('Matcha engelska ord med bildord')).toBeVisible();await page.getByRole('button',{name:'Nivå 2'}).click();await expect(page.getByText(/ENGELSKA · NIVÅ 2/)).toBeVisible()
  const pairId=await page.locator('.card').first().getAttribute('data-testid');if(!pairId)throw new Error('missing card id');const root=pairId.replace(/-[01]$/,'');await page.getByTestId(`${root}-0`).click();await page.getByTestId(`${root}-1`).click();await expect(page.getByText('1 stjärnor')).toBeVisible();await page.reload();await expect(page.getByText('1 stjärnor')).toBeVisible()
})
test('all four learning tracks expose playable pairs',async({page})=>{await page.goto('/');await page.getByRole('button',{name:'Spela'}).click();await page.getByRole('button',{name:'Parjakten'}).click();for(const name of ['Matte','Svenska','Engelska','Kul fakta']){await page.getByRole('button',{name:new RegExp(name)}).click();await expect(page.getByRole('region',{name:new RegExp(`Memory: ${name}`)})).toBeVisible();await expect(page.locator('.card')).toHaveCount(6)}})
test('shuffle rotates to a different set of learning pairs',async({page})=>{await page.goto('/');await page.getByRole('button',{name:'Spela'}).click();await page.getByRole('button',{name:'Parjakten'}).click();const before=await page.locator('.card').evaluateAll(cards=>cards.map(card=>card.getAttribute('data-testid')?.replace(/-[01]$/,'')).filter((id,index,items)=>id&&items.indexOf(id)===index));await page.getByRole('button',{name:'Blanda om'}).click();const after=await page.locator('.card').evaluateAll(cards=>cards.map(card=>card.getAttribute('data-testid')?.replace(/-[01]$/,'')).filter((id,index,items)=>id&&items.indexOf(id)===index));expect(after.sort()).not.toEqual(before.sort())})
test('PWA metadata is reachable',async({page,request})=>{await page.goto('/');await expect(page.locator('link[rel=manifest]')).toHaveAttribute('href','/manifest.webmanifest');expect((await request.get('/manifest.webmanifest')).ok()).toBe(true);expect((await request.get('/sw.js')).ok()).toBe(true)})
