import{useEffect,useState}from'react'
import{getTrack,tracks,type Difficulty,type TrackId}from'../../../game'
import{DifficultyControl}from'../../../components/DifficultyControl'
import{makeQuestion,type Question}from'../ticTacToe'
import{advance,createRun,TICK_MS,type Action,type Lane,type RunState}from'./runnerEngine'
import{jungleStages}from'./jungleRunContent'
import'./runner.css'
export function JungleRun({difficulty,onDifficultyChange,onWin}:{difficulty:Difficulty;onDifficultyChange:(value:Difficulty)=>void;onWin:()=>void}){const[trackId,setTrackId]=useState<TrackId>('math');const[stage,setStage]=useState(0);const[fun,setFun]=useState(false);const[tokens,setTokens]=useState(0);const[question,setQuestion]=useState<Question>(()=>makeQuestion('math',difficulty));const[run,setRun]=useState<RunState>(createRun);const[bossHits,setBossHits]=useState(0);const[message,setMessage]=useState<string>(jungleStages[0].description);const track=getTrack(trackId)
 const restart=(nextTrack=trackId,nextDifficulty=difficulty)=>{setTrackId(nextTrack);onDifficultyChange(nextDifficulty);setStage(0);setTokens(0);setQuestion(makeQuestion(nextTrack,nextDifficulty));setRun(createRun());setBossHits(0);setMessage(jungleStages[0].description)}
 const nextStage=()=>{const next=stage+1;if(next>2){onWin();setMessage('Djungeln är trygg! Du klarade hela äventyret.');return}setStage(next);setRun(createRun());setQuestion(makeQuestion(trackId,difficulty));setMessage(jungleStages[next].description)}
 useEffect(()=>{if(stage!==1||run.status!=='running')return;const timer=window.setInterval(()=>setRun(current=>advance(current,{},difficulty===1?12:16)),difficulty===1?TICK_MS+140:TICK_MS);return()=>clearInterval(timer)},[stage,run.status,difficulty])
 // oxlint-disable-next-line react-hooks/exhaustive-deps, react/set-state-in-effect -- stage transitions respond to the pure engine status
 useEffect(()=>{if(run.status==='clear')nextStage();if(run.status==='crashed'){setMessage('Nästan! Flykten börjar om.');setRun(createRun())}},[run.status])
 const answer=(option:string)=>{if(option!==question.correctAnswer){setMessage('Försök igen!');return}if(stage===0){const next=tokens+1;setTokens(next);if(next===3)nextStage();else{setQuestion(makeQuestion(trackId,difficulty));setMessage(`Bra! ${next} av 3 frön.`)}}else if(stage===2){const next=bossHits+1;setBossHits(next);if(next===3)nextStage();else{setQuestion(makeQuestion(trackId,difficulty));setMessage(`Skölden öppnades! ${next} av 3 träffar.`)}}}
 const move=(lane?:Lane,action?:Action)=>stage===1&&setRun(current=>advance(current,{lane,action},difficulty===1?12:16))
 const showQuestion=!fun&&(stage===0||stage===2)&&bossHits<3
 return <section className="runner-panel" aria-label="Djungellöpet"><section className="track-picker" aria-label="Välj ämne">{tracks.map(item=><button aria-pressed={item.id===trackId} className={item.id===trackId?'track active':'track'} onClick={()=>restart(item.id,difficulty)} key={item.id}><span>{item.shortName}</span><b>{item.name}</b></button>)}</section><section className="runner-hero"><div><p className="eyebrow">{track.name.toUpperCase()} · NIVÅ {difficulty}</p><h2>Djungellöpet</h2><p aria-live="polite">Bana {stage+1}: {jungleStages[stage]?.name}. {message}</p></div><div className="runner-actions"><DifficultyControl value={difficulty} onChange={level=>restart(trackId,level)}/><button aria-pressed={fun} className="reset" onClick={()=>setFun(value=>!value)}>{fun?'Lärläge':'Bara lek'}</button><button className="reset" onClick={()=>restart()}>Börja om</button></div></section><div className="stage-dots" aria-label={`Bana ${stage+1} av 3`}>{jungleStages.map((item,index)=><span className={index===stage?'active':''} key={item.name}>{index+1}</span>)}</div>{stage===1&&<><div className="runner-track" aria-label="Djungelbana">{([0,1,2]as Lane[]).map(lane=><button aria-label={`Spår ${lane+1}`} aria-pressed={run.lane===lane} onClick={()=>move(lane)} key={lane}>{run.lane===lane?'●':'·'}<small>{run.obstacles.some(item=>item.lane===lane)?'Hinder':'Fritt'}</small></button>)}</div><div className="runner-controls"><button onClick={()=>move(undefined,'jump')}>Hoppa</button><button onClick={()=>move(undefined,'duck')}>Ducka</button></div><progress aria-label="Banans framsteg" max={difficulty===1?12:16} value={run.distance}/></>}{showQuestion&&<section className="runner-question" aria-label="Kunskapsfråga"><p>{question.prompt}</p><div>{question.options.map(option=><button onClick={()=>answer(option)} key={option}>{option}</button>)}</div></section>}{fun&&stage!==1&&<button className="runner-next" onClick={nextStage}>Klara banan</button>}</section>}
